### ISSUE TITLE
Signing witness inputs: builtins.ValueError: witness scritpubkey is found for non-witness UTXO at index 1

### ISSUE THREAD

**Issue by AdamISZ** [Simplexum/python-bitcointx#45]
In testing wasabi-joinmarket compatibility, encountered this problem; read in a psbt [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/jmclient/jmclient/wallet.py#L1242) and then sign [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/jmclient/jmclient/wallet.py#L1277) (note: both participants in the payjoin are using p2wpkh, only), results in the above error. I did not previously encounter an error like this in testing, when I was using PSBTs with only WITNESS_UTXO fields.

This makes sense to me, because as I understand it, we now default to having the `utxo` field of PSBTs always be nonwitness (`CTransaction`) type, and the `PSBT_Input.sign()` function seems to use this field to decide whether to apply non-witness signing (and invalidates a case where the script pubkey is of witness type). This looks like a bug? (or did I miss something) (in case not obvious what I mean, to be explicit: the fact that the `utxo` field of a `PSBT_Input` is of type `CTransaction` does not mean the input is not witness type, but the code seems to say that it does).

https://github.com/Simplexum/python-bitcointx/blob/155a8aee04ea2d6dfae48f0eb3d8b74571d51d2e/bitcointx/core/psbt.py#L1063-L1066

**Comment by dgpv** [comment]
The utxo is taken like this: https://github.com/Simplexum/python-bitcointx/blob/155a8aee04ea2d6dfae48f0eb3d8b74571d51d2e/bitcointx/core/psbt.py#L890

So it should be CTxOut if `witness_utxo` is present

**Comment by dgpv** [comment]
Did you look at the decoded PSBT in question in python shell ? Does input at index 1 has `witness_utxo` field ?

Maybe add debug prints into `stream_deserialize()` for PSBT_Inputs after `read_psbt_keymap()` (or inside `read_psbt_keymap()` itself to see what is decoded

**Comment by AdamISZ** [comment]
Hi, sorry was afk for a bit. So first: yes, silly reading fail on my part, as to the origin of the `utxo` variable in that function.

Second, the PSBT concerned is like this (data below): it has an input which was taken from an earlier PSBT object, and that input had a NONWITNESS_UTXO field only (i.e. it didn't have a WITNESS_UTXO field). So that input has `utxo` set as a `CTransaction` but no witness_utxo data.
So it seems that's my basic problem, that Wasabi reasons as follows: we need the NONWITNESS_UTXO field to address the recent PSBT changes, and we don't need additional redundant information; then I take that `PSBT_Input.utxo` field and add it into the newly constructed coinjoin transaction, and it gets rejected when I'm going through the inputs in the call to `sign()`.

Unfortunately I cannot look directly at the data of this transaction, I only have the stack trace as per [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/698#issuecomment-705614593)) since I'm not running these two apps on testnet, but I do know that Wasabi sends its original PSBT with only NONWITNESS_UTXO data attached, see the example base64 [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/698#issue-499925131). (That is finalized, but it is the pre-payment in payjoin bip78, we are signing a new psbt with that input inserted but of course un-finalized).

Now that I understand it, I could manually insert the `witness_utxo` into the inputs as needed, but I'd rather do whatever is actually correct here.

**Comment by dgpv** [comment]
The example base64-encoded psbt that you linked to contains both `WITNESS_UTXO` and `NON_WITNESS_UTXO` fields (and also `FINAL_SCRIPTWITNESS`) field in its only input.

> it has an input which was taken from an earlier PSBT object, and that input had a NONWITNESS_UTXO field only (i.e. it didn't have a WITNESS_UTXO field). So that input has utxo set as a CTransaction but no witness_utxo data.

The encoded transaction can have only `NONWITNESS_UTXO` in its encoding and still have `witness_utxo` field in `PSBT_Input`, if other PSBT fields are present in the encoding that allow to say that this is indeed a witness UTXO. If there's no such data, we and no `WITNESS_UTXO` in encoded transaction, it will be deemed as non-witness.

You said that that input has utxo set as `CTransaction` but no `witness_utxo`. That means that the encoding for that input did not contain any of `WITNESS_SCRIPT`, `FINAL_SCRIPT_WITNESS`,`WITNESS_UTXO`. The only way to know if this is a witness input is then out-of-band.

**Comment by dgpv** [comment]
> I could manually insert the witness_utxo into the inputs as needed

you could do `psbt.set_utxo(None, i, force_witness_utxo=True)` to forcefully "witness-ize" the input.

**Comment by dgpv** [comment]
the 'None' means just use `self._utxo`.

Now that I think about this, maybe not the most intuitive thing, and this actually changed the semantics, as previously this would un-set the utxo, and now it won't have this effect. This seems like a mistake, but is an off-topic in this issue

**Comment by AdamISZ** [comment]
> The example base64-encoded psbt that you linked to contains both WITNESS_UTXO and NON_WITNESS_UTXO fields (and also FINAL_SCRIPTWITNESS) field in its only input (and has witness_utxo property populated when decoded)

Right, my mistake. It is yet another instance of the logic failing because I originally assumed only one of the two were included; my `human_readable_psbt` function made this assumption; when I corrected it I see it.

> You said that that input has utxo set as CTransaction but no witness_utxo. That means that the encoding for that input did not contain any of WITNESS_SCRIPT, FINAL_SCRIPT_WITNESS,WITNESS_UTXO. The only way to know if this is a witness input is then out-of-band.

This part I only partially understand, if the `utxo` is type `CTransaction` then presumably it's possible to deduce that the input is segwit type *if* the scriptPubKey of the referenced output is not p2sh, even without the other fields. But that's academic (I know that this "corner case" is addressed in other parts of the recent patch).

**Comment by dgpv** [comment]
> the witness_utxo was included here.

But the error is also about input at index 1, while the linked base64-encoded psbt had only one input

**Comment by AdamISZ** [comment]
> > the witness_utxo was included here.
> 
> But the error is also about input at index 1, while the linked base64-encoded psbt had only one input

That's a detail of the complexity of this case; we have *that* psbt as "input" (a fully signed pre-payment); and then we grab that input and include it in the new payjoin PSBT.

**Comment by AdamISZ** [comment]
So .. I need to include the provided `witness_utxo` field when I "port" this input from the old (fully signed non coinjoin) PSBT that the sender provided, to the new payjoin PSBT (to which I add my own input(s)).

**Comment by dgpv** [comment]
Sorry, I do not fully understand your context.

who provides `witness_utxo` ?

Will supplying `always_include_witness_utxo=True` to `serialize()` somewhere could help you ?

**Comment by dgpv** [comment]
(oh, pleas ignore last message, `always_include_witness_utxo` is true by default)

**Comment by AdamISZ** [comment]
OK, I realise the problem comes in here:

https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/c75a5b10de30ade18ea0916176c6ae86384e5aa3/jmclient/jmclient/wallet.py#L1203-L1208

... basically, same issue: I was assuming only one of the two, and call `set_utxo` with whichever one is given.

Context:
sender sends a finalized psbt which is checked to be a valid payment of the chosen amount.
receiver (in this case, JM code) after checking that, takes the input(s) from that tx, and creates a brand new psbt with those inputs, and his own inputs, to recreate the payment as a coinjoin. There are a bunch of rules (BIP78) but that's a sidetrack. Is it clear now?

**Comment by dgpv** [comment]
The problem is that the call to `input.set_utxo()` does not supply unsigned_tx. Without it, there is nowhere to extract the witness utxo from

**Comment by dgpv** [comment]
Or rather, no way to locate the output to extract the witness utxo from supplied `CTransaction`

**Comment by AdamISZ** [comment]
Ah yes, that makes perfect sense, I see. If I read the code correctly, if I provide that, it will populate witness_utxo (due to call of `check_witness_utxo_spk`).

**Comment by dgpv** [comment]
btw, I see that you actually have unsigned_tx earlier in the code (`new_psbt = btc.PartiallySignedTransaction(unsigned_tx=tx)`) so you can just supply it, or use `new_psbt.set_utxo(spent_outs[i], i)`

**Comment by dgpv** [comment]
> if I provide that, it will populate witness_utxo (due to call of check_witness_utxo_spk)

yes

**Comment by AdamISZ** [comment]
> btw, I see that you actually have unsigned_tx earlier in the code (`new_psbt = btc.PartiallySignedTransaction(unsigned_tx=tx)`) so you can just supply it, or use `new_psbt.set_utxo(spent_outs[i], i)`

But that is unsigned_tx of *this* PSBT, whereas we need the unsigned_tx of the input being spent, right? I think that's why I didn't do it originally.

**Comment by dgpv** [comment]
re unexpectedly changed `set_utxo(None, ...)` semantics, I opened separate issue #47

**Comment by dgpv** [comment]
> But that is unsigned_tx of this PSBT, whereas we need the unsigned_tx of the input being spent, right? I think that's why I didn't do it originally.

These `unsigned_tx`'s should be in-sync, no ?

**Comment by AdamISZ** [comment]
Yeah, see above, just got confused.

**Comment by dgpv** [comment]
> wait, even if it's p2sh, it is possible right, because utxo would be a fully signed transaction, so would have the witness

In this case we are interested in the output of the `CTransaction` that is the utxo. This output is what is spend by the input that we want to know the witness status of. If it is a p2sh output, then the only way we can infer that it is was p2sh_p2wsh is if our psbt input also has `witness_script` or `final_script_witness`.

And by the way if your `new_psbt` inputs can be missing  `witness_script` or `final_script_witness` and be spending p2sh outputs, you can hit this corner case. If this is possible, them maybe you want to store that 'witness-ness' flags somewhere along `spent_outs` and supply it to `force_witness_utxo` kwarg of `set_utxo()`.

OTOH, I think it is likely that correctly-constructed inputs will bear `witness_script`, so probably this corner case will not emerge.

**Comment by AdamISZ** [comment]
> In this case we are interested in the output of the CTransaction that resides in the NON_WITNESS_UTXO, and the input witnesses are irrelevant

Yes, it's clear. Sorry for confusion.
