### ISSUE TITLE
Signing a PSBT with some inputs not having utxo throws ValueError

### ISSUE THREAD

**Issue by AdamISZ** [Simplexum/python-bitcointx#52]
I was previously using `sign()` method of `psbt.PartiallySignedTransaction` with a keystore containing keys for only some inputs, and it was working fine, but I now have a use case where some of the *other* inputs (which I'm not signing and don't have keys for) are required (see BIP78) to *not* have the utxo field filled in. When I call `sign()` in this case, those inputs throw the above mentioned ValueError (which btw has a trivial typo: `'utxo is not set for of PSBT_Input at index {self.index}'`).

Currently I only have the ugly option of signing first, then deleting the utxo field. But unless I missed something, it should be possible to call `sign()` on the overall PSBT without it throwing an Exception (though I suppose, it could certainly be an option).

**Comment by dgpv** [comment]
Yes, it looks like we should just return `None` if utxo is not set, now it always raises an exception

https://github.com/Simplexum/python-bitcointx/blob/41e25ed4d3c45097c90c640c91e201405280a33f/bitcointx/core/psbt.py#L925-L929

a few lines above there's also a check if the index is set on UTXO:

https://github.com/Simplexum/python-bitcointx/blob/41e25ed4d3c45097c90c640c91e201405280a33f/bitcointx/core/psbt.py#L921-L923

`index` on the input may be unset if someone created `PSBT_Input` directly and did not supply or did not set the index.

It seems to me that conceptually, in both of this cases we can just return "None" and not throw execption.

The only situation where throwing an exception seems to be of value is when someone needs to make sure that all inputs are signable. But "unsignable" inputs return None in other cases such as unrecognized script, and the check can be accomplished just by iterating over `psbt.inputs` doing `if inp.sign(...) is None:`

I think I will just replace `raise ValueError(...)` with `return None` in both cases: #53 

Let me know if you think that there's a better way to handle this

**Comment by AdamISZ** [comment]
From my view, I think returning None is right. A caller can always inspect the SignResult object to check (I think?) that the result is as intended. I believe I agree also about `index`; I don't have such a use case right now, but I could maybe imagine it.

**Comment by dgpv** [comment]
I released `v1.1.1.post2` with the fix
