### ISSUE TITLE
Can DeserializationValueBoundsError be triggered by a valid tx?

### ISSUE THREAD

**Issue by AdamISZ** [Simplexum/python-bitcointx#56]
From a Joinmarket user report, we saw this exception raised:

```
bitcointx.core.serialize.DeserializationValueBoundsError: non-canonical compact size for variable integer: 0x3e4a9d70215fc30a more than 0x2000000
```

This came from a CTransaction.deserialize call:

```
btc.CMutableTransaction.deserialize(
  File "...bitcointx/core/serialize.py", line 147, in deserialize
    r = cls.stream_deserialize(fd, **kwargs)
  File "...bitcointx/core/__init__.py", line 113, in wrapper
    return fn(*args, **kwargs)
  File "...bitcointx/util.py", line 330, in wrapper
    return fn(*args, **kwargs)
  File "...bitcointx/core/__init__.py", line 1113, in stream_deserialize
    wit = CTxWitness.stream_deserialize(f, num_inputs=len(vin),
  File "...bitcointx/util.py", line 330, in wrapper
    return fn(*args, **kwargs)
  File "...bitcointx/core/__init__.py", line 926, in stream_deserialize
    vtxinwit = tuple(CTxInWitness.stream_deserialize(f, **kwargs)
  File "...bitcointx/core/__init__.py", line 926, in <genexpr>
    vtxinwit = tuple(CTxInWitness.stream_deserialize(f, **kwargs)
  File "...bitcointx/util.py", line 330, in wrapper
    return fn(*args, **kwargs)
  File "...bitcointx/core/__init__.py", line 815, in stream_deserialize
    scriptWitness = script.CScriptWitness.stream_deserialize(f, **kwargs)
  File "...bitcointx/core/script.py", line 1158, in stream_deserialize
    stack = tuple(BytesSerializer.stream_deserialize(f, **kwargs)
  File "...bitcointx/core/script.py", line 1158, in <genexpr>
    stack = tuple(BytesSerializer.stream_deserialize(f, **kwargs)
  File "...bitcointx/core/serialize.py", line 328, in stream_deserialize
    datalen = VarIntSerializer.stream_deserialize(f, **kwargs)
  File "...bitcointx/core/serialize.py", line 309, in stream_deserialize
    raise DeserializationValueBoundsError(
bitcointx.core.serialize.DeserializationValueBoundsError: non-canonical compact size for variable integer: 0x3e4a9d70215fc30a more than 0x2000000
```

So, pretty clearly this *could* be caused by simply having a corrupted (somehow) serialized transaction, but my question is, is there any, however obscure, case where this could occur from a valid Bitcoin transaction?

Obviously diagnosing this particular case would ideally involve looking at the serialized tx that was passed in, but generally we don't ask users for any identifying data, so I'm just asking the question in abstract for now.

(Edit: I should mention that the call occurs here, note that it is the "hex" field of a gettransaction RPC call, which is why we would always expect it to be an actual/not corrupt or malformed serialized transaction:

https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/81982c729f4bb8f702b6c73f4685463c97cb6e4a/jmclient/jmclient/blockchaininterface.py#L294-L302

**Comment by dgpv** [comment]
The exception happens here: https://github.com/Simplexum/python-bitcointx/blob/3215fc9670268e19dae92a58a85ab47a8d2ba788/bitcointx/core/serialize.py#L304-L313

This corresponds to the following code in Bitcoin Core: https://github.com/bitcoin/bitcoin/blob/409afd715351592a00ad5a0e5400858f6e734eef/src/serialize.h#L344-L346

It is possible that in some places the decoding calls `ReadCompactSize` with `range_check = false`, but bitcointx does not call deserialize with `allow_full_range = True`.

Needs investigation.

**Comment by dgpv** [comment]
The ability to skip this check was added to `ReadCompactSize` in October: https://github.com/bitcoin/bitcoin/commit/1d3ec2a1fda7446323786a52da1fd109c01aa6fb

**Comment by dgpv** [comment]
But the relaxation of this check is only happens when processing `ADDRV2_FORMAT` for BIP155, so should not matter for transaction decoding.

The python code seems to be corresponding to the C++ code, so I'd say the problem is somewhere in the other part of data.

If the user has the transaction hex data, maybe good idea could be to ask them to try `decoderawtransaction` RPC of Core to check if it is really correct

**Comment by AdamISZ** [comment]
I agree that it is certainly far more likely to be an error outside this library, feeding in invalid transaction data. But I thought asking the question in abstract is certainly worthwhile, as if such a thing were possible, I'd certainly need to know about it.

Thanks for looking into it!

**Comment by dgpv** [comment]
I think we cannot fully exclude the possibility that the problem is in the lib, because the problem might be in incorrect deserialization code before the execution got to this compact integer deserialization. But without looking data that caused the problem, it would be hard to search for the error - would need to audit almost all of serialization code. If we could have at least some definitive result (even without having the data at hand), like "there exists a hex string is parsed successfully by decoderawtransaction, but fails the parse with bitcointx", then putting extra scrunity on bitcointx deserialization code might be justified

**Comment by AdamISZ** [comment]
The user was kind enough to give me the evidence, I can now see that the error is in Joinmarket code; the transaction being deserialized contained marker bytes (which are not actually a valid part of a transaction), which aren't valid. So, closing. Sorry for the trouble.
