### ISSUE TITLE
BIP32 test vector 5 should be added to tests and checked

### ISSUE THREAD

**Issue by kristapsk** [Simplexum/python-bitcointx#58]
See https://github.com/bitcoin/bips/pull/921 and https://github.com/bitcoin/bitcoin/pull/22836.

**Comment by dgpv** [comment]
Thanks for reminder, bitcointx was missing one the check ("'when depth is 0, child_number must also be 0")

Fixed in https://github.com/Simplexum/python-bitcointx/commit/e184f73c270c4f975e1a4a4896e087a5d8465ac2

**Comment by kristapsk** [comment]
Any plans for a new release? Would like to add these test vectors to JoinMarket test suite too.

**Comment by dgpv** [comment]
This is small change and not a very important fix, I think. Not enough to warrant new release

I recently got taproot working (not yet pushed to github), and maybe the new release with support of taproot close enough. But I will need to iron out the new APIs before that. I'll update on taproot progress in this issue: https://github.com/Simplexum/python-bitcointx/issues/57

**Comment by kristapsk** [comment]
I was in impression that taproot will not happen soon because of currently unstable libsecp256k1 ABI, but if we can already see some light at the end of the tunnel, that's great news!

**Comment by dgpv** [comment]
Well, the ABI problem is certainly there. It may or may not prevent the new release. I've made a new issue to discuss that: https://github.com/Simplexum/python-bitcointx/issues/59
