### ISSUE TITLE
How to handle libsecp256k1 ABI non-guarantees of stability

### ISSUE THREAD

**Issue by dgpv** [Simplexum/python-bitcointx#59]
taproot support is dependent on libsecp module that is experimental and can change its ABI (see https://github.com/Simplexum/python-bitcointx/issues/57#issuecomment-915314718)

and in general the ABI of libsecp is not a guaranteed thing, because they don't have releases yet

other projects just include particular version of libsecp source and build their own library, but that makes the package much havier and adds a lot of potential problems on installation related to compiling native code.

projects can just handle the compilation themselves and load their version of the library directly by supplying path to `load_secp256k1_library()`, via `set_custom_secp256k1_path()` or via `LD_LIBRARY_PATH` environment variable (on systems where it has effect)

This issue is for discussing the ways to handle the problem. What is the best way to handle this to enable the release that supports taproot ?

1) Bundle libsecp with bitcontx and compile on install (anyone willing to help writing the needed code for that ?)
2) Recommend using particular commit of libsecp with bitcointx, tell projects to handle supplying the correct version of the library themselves at runtime
3) Leave as it is now - the hack that checks for `secp256k1_schnorrsig_sign_custom` as an indicator that the library version is after some particular commit and hope no other changes will happen
4) Do not merge taproot support into master branch and not do release until there's stable ABI for schnorr signatures in libsecp

**Comment by dgpv** [comment]
The distro-installed version of libsecp is unlikely to have experimental modules enabled, so anyone who would want to use schnorr sigs will need to compile themselves anyway (until the module becomes non-experimental, at least), so I'm inclining towards combining the options 2 and 3.

**Comment by dgpv** [comment]
The safest is the option 4, of course. But there's no timeline when such stabilization would happen, AFAIK.

**Comment by dgpv** [comment]
We could make enabling the scnorr signature support explicit with some function, like `enable_experimental_schnorrsig_support()`. Calling that function will be the indication that the caller is aware of the issue and is certain that the compatible version of the library will be loaded

**Comment by scgbckbone** [comment]
1. is too heavy imo; and I would say that anyone playing with this lib can compile for themselves so 2. seems pretty reasonable (update README to state what is the minimal version that one needs); 3. works already so why changing it and to 4. I'm also waiting for release but cannot find any info on timeline - meh

**Comment by dgpv** [comment]
The chosen path is:

- stating the 'recommended' commit in README.md (this change is already in master)
- experimental modules must be enabled explicitly with `allow_secp256k1_experimental_modules()` or PYTHON_BITCOINTX_ALLOW_LIBSECP256K1_EXPERIMENTAL_MODULES_USE=1 environment variable (this change is in taproot branch)

**Comment by 3nprob** [comment]
Perhaps this can be revisited and a `pyproject.yaml` approach considered?
- #87
