### ISSUE TITLE
Potential problem with RIPEMD160 removal from newer OpenSSL versions by default

### ISSUE THREAD

**Issue by kristapsk** [Simplexum/python-bitcointx#64]
See https://github.com/bitcoin-core/HWI/issues/305 and https://github.com/openssl/openssl/issues/16994.

Bitcoin Core solved it by writing own pure Python RIPEMD160 implementation (see https://github.com/bitcoin/bitcoin/pull/23716), but it's meant to be used only for tests as it isn't constant time.

**Comment by dgpv** [comment]
#65 should solve this (taken the code from Core's test framework)

I'm not sure if 'constant time' is relevant here. Hash functions is not supposed to work with any secret data.

It will likely be much slower than openssl implementation that is used by python, but given that ripemd160 is already not available from python.hashlib in some linux distributions, we'll have to bear this this.

**Comment by dgpv** [comment]
The Core's implementation is described as "Test-only" in https://github.com/bitcoin/bitcoin/commit/68ca8677e039a60b9f51938987d784cb58a3c995

But here we would be using it in the 'body' of the library, not only in tests.

We already use code from Core's test framework, for example,  `bitcointx/segwit_addr.py`. But `bitcointx/segwit_addr.py` is described as 'Reference implementation'.

I wonder if it is OK to use the Core's test framework implementation of ripemd160. On one hand, it passes the tests and is quite simple. On the other hand, it is "Test only".

The code from Electrum (https://github.com/spesmilo/electrum/blob/0df05dd914c823acae1828cad3b20bdeb13150e9/electrum/ripemd.py) is more complex, and has comments like "parallel round 1", but I doubt that it is any faster, there's no automatic parallelization in python AFAIK, as it could be done by the C/C++ compiler that the original code seems to be written for. This code does not claim to be 'Test-only', though.
