### ISSUE TITLE
sign-psbt.py example does not support electrum's testnet xpub encoding for p2wsh

### ISSUE THREAD

**Issue by kanzure** [Simplexum/python-bitcointx#71]
For regtest/testnet mode, bitcointx raises an error when attempting to sign an electrum-generated PSBT because of the presence of an xpub with prefix 0x043587cf (tpub) and does not accept an xpub with prefix 0x02575483 (Vpub).

https://electrum.readthedocs.io/en/latest/xpub_version_bytes.html#specification

I think the simplest solution here would be some xpub type coercion when the user calls the signer with a special flag? Or even type coercion based on `--regtest/--mainnet` flags.

That said, @darosior [mentions](https://github.com/darosior/python-bip32/issues/26#issuecomment-1222713918):
> hardcoding of specific script types inside the encoding of an extended public key is an unscalable and terrible layer violation

**Comment by dgpv** [comment]
The exception should be raised within deserialization code, not within the signing code.

Please check if the following PR would fix your problem: https://github.com/Simplexum/python-bitcointx/pull/72 

`PartiallySignedTransaction.deserialize()` now accept optional arg `acceptable_xpub_prefixes` which is the list of 4-byte prefixes acceptable for xpubs. Please look at the test code in PR for examples.

**Comment by dgpv** [comment]
Please note that the serialization will use standard prefixes, so when PSBT with non-standard prefixes is deserialized and then serialized again it will differ from the original

**Comment by dgpv** [comment]
@kanzure, has #72 fixed the problem ?
