### ISSUE TITLE
libbitcoinconsensus undefined symbol

### ISSUE THREAD

**Issue by JeremyRand** [Simplexum/python-bitcointx#74]
Trying to use the libbitcoinconsensus that Bitcoin Core's Guix binaries ship with is giving me this error.

~~~
ImportError: Cannot import consensus library: ./libbitcoinconsensus.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
~~~

Is that expected behavior?  Your docs say to build from source, but it's not obvious to me why upstream binaries shouldn't work.  I'm running Debian Bullseye if it matters.

**Comment by dgpv** [comment]
Could it be that you are using the `./libbitcoinconsensus.so` from Debian Bullseye package on other system, and there is a different version of `libstdc++` on this system, which does not contain this symbol ?

**Comment by JeremyRand** [comment]
Totally possible (in fact seems likely), but I don't get this error when running the `bitcoind` binary from that download, and AFAIK Bitcoin Core's Guix binaries are supposed to avoid this by linking statically.  Worth filing a bug with Bitcoin Core?

**Comment by dgpv** [comment]
I guess this is more of an issue of this Guix package, if the packaged binaries are supposed to run regardless of glibc version, then `libbitcoinconsensus.so` should also run regardless of it. Or maybe this Guix package comes with required .so files that are needed to be pointed to by `LD_LIBRARY_PATH` ?

**Comment by dgpv** [comment]
Closing because this is not relevant to this library. This is an issue of system dynamic library loader and availability of required libraries with needed symbols. The python library do not have any control over this. The following code can be used to test for the issue:

```
import ctypes.util
path = ctypes.util.find_library('bitcoinconsensus')  # or supply concrete path
ctypes.cdll.LoadLibrary(path)
```
