### ISSUE TITLE
Issues with configure bitcointx to work with libsecp256k1

### ISSUE THREAD

**Issue by katsucodes247** [Simplexum/python-bitcointx#83]
Hi, I'm unable to get bitcointx to use `libsecp256k1`.

I've installed bitcointx via pip: `pip install python-bitcointx`

I have `libsecp256k1` installed:

```sh
$ ldconfig -p | grep libsecp     
libsecp256k1.so.0 (libc6,x86-64) => /lib64/libsecp256k1.so.
libsecp256k1.so (libc6,x86-64) => /lib64/libsecp256k1.so
```

```sh
$ ls /usr/lib64/libsecp256k1.so.0
/usr/lib64/libsecp256k1.so.0
```

This is how I load it and I get the RuntimeError when trying to get `xonly_pub`.

```py
import bitcointx as btc
btc.set_custom_secp256k1_path("/usr/lib64/libsecp256k1.so.0")
pvt_key = PrivateKey(12345, network="regtest")
from bitcointx.wallet import CCoinKey

CCoinKey.from_secret_bytes(bytes([6]*32)).xonly_pub
```

```
bitcointx/core/key.py", line 2021, in __new__
    raise RuntimeError(
RuntimeError: x-only pubkey handling functions from libsecp256k1 is not available. configure it libsecp256k1 with --enable-module-extrakeys
```

Any help/pointers on how to solve this issue would be greatly appreciated.

**Comment by dgpv** [comment]
You need to upgrade libsecp256k1

`objdump -T /path/to/libsecp256k1.so | grep secp256k1_xonly_pubkey_parse` should show the symbol. If it shows nothing, that means that version of the library is too old

Latest version of libsecp256k1 is v0.4.1

Automatic tests of python-bitcointx currently use libsecp256k1 v0.4.0

One problem you might encounter is that latest versions of python seem to be ignoring `LD_LIBRARY_PATH` environment variable.

If changing a system-installed library to newer version is not an option, you will need to compile [libsecp256k1](https://github.com/bitcoin-core/secp256k1) from source and will likely need to do `bitcoints.set_custom_secp256k1_path("/path/to/libsecp256k1.so")` to tell bitcointx to load the correct library

**Comment by katsucodes247** [comment]
I can confirm that `secp256k1_xonly_pubkey_parse` was not available, I've uninstalled the system's `libsecp256k1` and targeted `libsecp256k1` from the latest OS release which seems to have been v0.4.1. After doing so, I'm not getting the error anymore.

TIL something new. Thank you @dgpv!
